[package]
name = "source-db"
version = "0.1.0"
authors = ["quickshell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compress = "0.1"
bincode = "1.0"
serde = { version = "1", features = ["derive"] }